* basher
** Notes
   .bash_profile is called for login shells, and .bashrc is called for non-login shells. If a variable is already defined before .bash_profile (c.f. $PATH) and the value is changed, the variable and its value will be inherited by the subshell. However newly defined variables in .bash_profile will not be inherited by the subshells, thus should be defined in .bashrc. Aliases and shell functions are not inherited, thus should be defined in .bashrc. To make those aliases and shell functions available to login shells, simply call .bashrc from .bash_profile.

   To make it convenient to reuse these configuration on multiple machines, where there may be specific local .bash_profile and .bashrc settings, two files are created: ._bash_profile and ._bashrc. Source ._bash_profile from the local .bash_profile, and ._bashrc from the local .bashrc. Private and local specific configurations should be kept in the local machine specific .bash_profile and .bashrc files on those specific machines and not shared in this library.

(Some systems have a convention to use a .bash_aliases file and the system-specific .bash_profile and .bashrc call the .bash_aliases file.)

** Bash Profile (._bash_profile.sh)
   :PROPERTIES:
   :header-args: :tangle ~/._bash_profile.sh :comments org
   :END:
*** ssh
    #+BEGIN_SRC sh
      #http://mah.everybody.org/docs/ssh
      #https://stackoverflow.com/questions/18880024/start-ssh-agent-on-login
      SSH_ENV="$HOME/.ssh/environment"

      function start_agent {
	  echo "Initialising new SSH agent..."
	  /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
	  echo succeeded
	  chmod 600 "${SSH_ENV}"
	  . "${SSH_ENV}" > /dev/null
	  /usr/bin/ssh-add;
      }

      # Source SSH settings, if applicable

      if [ -f "${SSH_ENV}" ]; then
	  . "${SSH_ENV}" > /dev/null
	  #ps ${SSH_AGENT_PID} doesn't work under cywgin
	  ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
	      start_agent;
	  }
      else
	  start_agent;
      fi

    #+END_SRC
     
** Bashrc (._bashrc.sh)
   :PROPERTIES:
   :header-args: :tangle ~/._bashrc.sh :comments org
   :END:

*** History
   #+BEGIN_SRC sh
     # History
     export HISTFILESIZE=20000
     export HISTSIZE=10000
     shopt -s histappend
     # Combine multiline commands into one in history
     shopt -s cmdhist
     # Ignore duplicates, ls without options and builtin commands
     HISTCONTROL=ignoredups
     export HISTIGNORE="&:ls:[bf]g:exit"

   #+END_SRC
*** Use trash instead of delete
   #+BEGIN_SRC sh
     # Aliases for trash-cli
     alias rm='echo "Do not use rm, instead use del which is aliased to trash-put"'
     alias del='trash-put'

   #+END_SRC
*** Convenience aliases
   #+BEGIN_SRC sh
     # Aliases for ls
     alias ll='ls -Alh'
     alias la='ls -lah'
     alias l='ls -CFlh'
     alias lsd="ls -alF | grep /$"
     alias lr='ls -CFlhAR'

     # Miscellaneous Aliases
     alias c='clear'
     alias h="history|grep "
     alias f="find . |grep "

     # Directory navigation
     alias ..='cd ..'
     alias ...='cd ../..'
     alias ....='cd ../../..'
     alias .....='cd ../../../..'

     # Files sizes
     alias diskspace="du -S | sort -n -r |more"

     # Show me the size (sorted) of only the folders in this directory
     alias folders="find . -maxdepth 1 -type d -print | xargs du -skh | sort -rn"

   #+END_SRC
*** Convenience functions
    #+BEGIN_SRC sh
      # Make directory then cd
      mcd () { mkdir -p $1; cd $1; }

      # Archives
      function extract {
	  if [ -z "$1" ]; then
	      # display usage if no parameters given
	      echo "Usage: extract <path/file_name>.<zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz>"
	      echo "       extract <path/file_name_1.ext> [path/file_name_2.ext] [path/file_name_3.ext]"
	      return 1
	  else
	      for n in $@
	      do
		  if [ -f "$n" ] ; then
		      case "${n%,}" in
			  ,*.tar.bz2|*.tar.gz|*.tar.xz|*.tbz2|*.tgz|*.txz|*.tar) 
			      tar xvf "$n"       ;;
			  ,*.lzma)      unlzma ./"$n"      ;;
			  ,*.bz2)       bunzip2 ./"$n"     ;;
			  ,*.rar)       unrar x -ad ./"$n" ;;
			  ,*.gz)        gunzip ./"$n"      ;;
			  ,*.zip)       unzip ./"$n"       ;;
			  ,*.z)         uncompress ./"$n"  ;;
			  ,*.7z|*.arj|*.cab|*.chm|*.deb|*.dmg|*.iso|*.lzh|*.msi|*.rpm|*.udf|*.wim|*.xar)
			      7z x ./"$n"        ;;
			  ,*.xz)        unxz ./"$n"        ;;
			  ,*.exe)       cabextract ./"$n"  ;;
			  ,*)
			      echo "extract: '$n' - unknown archive method"
			      return 1
			      ;;
		      esac
		  else
		      echo "'$n' - file does not exist"
		      return 1
		  fi
	      done
	  fi
      }

      # Colors
      # http://misc.flogisoft.com/bash/tip_colors_and_formatting
      bash-color-16() {
	  for clbg in {40..47} {100..107} 49 ; do
	      #Foreground
	      for clfg in {30..37} {90..97} 39 ; do
		  #Formatting
		  for attr in 0 1 2 4 5 7 ; do
		      #Print the result
		      echo -en "\e[${attr};${clbg};${clfg}m ^[${attr};${clbg};${clfg}m \e[0m"
		  done
		  echo #Newline
	      done
	  done
      }

      bash-color-256() {
	  for fgbg in 38 48 ; do #Foreground/Background
	      for color in {0..256} ; do #Colors
		  #Display the color
		  echo -en "\e[${fgbg};5;${color}m ${color}\t\e[0m"
		  #Display 10 colors per lines
		  if [ $((($color + 1) % 10)) == 0 ] ; then
		      echo #New line
		  fi
	      done
	      echo #New line
	  done
      }

      make-scratch-dir () {
	  local name="$1"
	  local pattern='^[a-z0-9\\-]+$'
	  if [[ "$#" != 1 ]]; then
	      echo "Usage: make-scratch-dir <name>" 1>&2
	      return 1
	  elif [[ ! "$name" =~ $pattern ]]; then
	      echo "Invalid name: ${name}"
	  fi
	  local full_path="$HOME/tmp/scratch/$(date +%Y%m%d-%H%M%S)-${name}"
	  mkdir -p "${full_path}"
	  pushd "${full_path}"
	  echo "Now in temp dir: ${full_path}"
      }

    #+END_SRC
*** Node/NVM
    Don't need this as nvm-install.sh will append to the .bashrc automatically as it depends on local configuration
   #+BEGIN_SRC sh :tangle no
     # Node
     export NVM_DIR="$HOME/.nvm"
     [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm
     export PATH=$PATH:$HOME/.nvm/versions/node/v8.5.0/bin
     [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
   #+END_SRC

*** Git functions
   #+BEGIN_SRC sh
     function git_local_config {

	 if [[ -n $GIT_USER_EMAIL && -n $GIT_USER_NAME ]]
	 then
	     git config --local user.email "$GIT_USER_EMAIL"
	     git config --local user.name "$GIT_USER_NAME"
	 fi

     }


   #+END_SRC
